In [4]:
getwd()

[1] "C:/Users/gpalghat006/Documents/GitHub/datasciencecoursera"

In [1]:
read.csv("test.csv", header = TRUE, sep=",")

ID Name             Age Sex Address                               
1 1  John Doe         22  m   one rob street, GA                    
2 2  Mango Madayan    33  m   12 winder word, collingwood, ga, 30034
3 3  Srivats Gowswami 44  m   5 RN E23, UK                          
4 4  Dena Smith       55  f   33 George st, washington DC           
5 5  Jane Doe         66  f   89 Marchicial st, toronto, Canada

In [16]:
x<-list(foo=1:4, bar=0.6, baz="hello")
x[c(1,3)]  #Single bracket gives a list, double backets the value

$foo
[1] 1 2 3 4

$baz
[1] "hello"

In [15]:
x[["bar"]]

[1] 0.6

In [19]:
x<-matrix(1:6,2,3)
x
x[1,2]
x[2,1]

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[1] 3

[1] 2

In [20]:
x[1,1,drop=FALSE]

[,1]
[1,] 1

In [23]:
x<-c(1,2,NA,4,NA,5)
bad <-is.na(x)
x[!bad]

[1] 1 2 4 5

In [25]:
x<-c(1,2,NaN,4,NaN,5)
bad <-is.na(x)
x[!bad]

[1] 1 2 4 5

In [41]:
y<-matrix(rep(10,16),4,4)
x<-matrix(1:2, 4,4)
x
y
x*y
x/y
x%*%y

[,1] [,2] [,3] [,4]
[1,] 1    1    1    1   
[2,] 2    2    2    2   
[3,] 1    1    1    1   
[4,] 2    2    2    2

[,1] [,2] [,3] [,4]
[1,] 10   10   10   10  
[2,] 10   10   10   10  
[3,] 10   10   10   10  
[4,] 10   10   10   10

[,1] [,2] [,3] [,4]
[1,] 10   10   10   10  
[2,] 20   20   20   20  
[3,] 10   10   10   10  
[4,] 20   20   20   20

[,1] [,2] [,3] [,4]
[1,] 0.1  0.1  0.1  0.1 
[2,] 0.2  0.2  0.2  0.2 
[3,] 0.1  0.1  0.1  0.1 
[4,] 0.2  0.2  0.2  0.2

[,1] [,2] [,3] [,4]
[1,] 40   40   40   40  
[2,] 80   80   80   80  
[3,] 40   40   40   40  
[4,] 80   80   80   80

In [46]:
z<-c(FALSE,4)
typeof(z)
l<-c(TRUE,4)
typeof(l)

[1] "double"

[1] "double"

In [57]:
x <- c(1,3, 5) 
y <- c(3, 2, 10)
#x
#y
#merge(x,y)
l<-rbind(x,y)
l

[,1] [,2] [,3]
x 1    3     5  
y 3    2    10

In [56]:
l[1,2]

x 
3

In [58]:
x <- list(2, "a", "b", TRUE)
x
x[2]

[[1]]
[1] 2

[[2]]
[1] "a"

[[3]]
[1] "b"

[[4]]
[1] TRUE

[[1]]
[1] "a"

In [59]:
x[[2]]

[1] "a"

In [92]:
x<-read.csv("hw1_data.csv", header = TRUE, sep=",")
#colnames(x)
#x[1:2,]
#n=nrow(x)
#tail(x,n=2)
#head(x,n=47)
#x[[47]]
#x["Ozone"]
#bad <-is.na(x["Ozone"])
#nrow(!bad)
#a<-table(x["Ozone"])
#a[names(a)=='NA']
count(x["Ozone"])

ERROR: Error in count(x["Ozone"]): could not find function "count"


In [106]:
#library(plyr)
#?count
#count(x["Ozone"])
l<-subset(x["Ozone"], x["Ozone"]!="NA")
#mean(l$Ozone)
#mean(l[,1])
mean(l[["Ozone"]])

[1] 42.12931

In [117]:
m<-subset(x,x["Ozone"]>31 & x["Temp"]>90)
m
mean(m[["Solar.R"]])

Ozone Solar.R Wind Temp Month Day
69   97   267     6.3  92   7      8 
70   97   272     5.7  92   7      9 
120  76   203     9.7  97   8     28 
121 118   225     2.3  94   8     29 
122  84   237     6.3  96   8     30 
123  85   188     6.3  94   8     31 
124  96   167     6.9  91   9      1 
125  78   197     5.1  92   9      2 
126  73   183     2.8  93   9      3 
127  91   189     4.6  93   9      4

[1] 212.8

In [119]:
z<-subset(x,x["Month"]==6)
z
mean(z[["Temp"]])

Ozone Solar.R Wind Temp Month Day
32 NA    286      8.6 78   6      1 
33 NA    287      9.7 74   6      2 
34 NA    242     16.1 67   6      3 
35 NA    186      9.2 84   6      4 
36 NA    220      8.6 85   6      5 
37 NA    264     14.3 79   6      6 
38 29    127      9.7 82   6      7 
39 NA    273      6.9 87   6      8 
40 71    291     13.8 90   6      9 
41 39    323     11.5 87   6     10 
42 NA    259     10.9 93   6     11 
43 NA    250      9.2 92   6     12 
44 23    148      8.0 82   6     13 
45 NA    332     13.8 80   6     14 
46 NA    322     11.5 79   6     15 
47 21    191     14.9 77   6     16 
48 37    284     20.7 72   6     17 
49 20     37      9.2 65   6     18 
50 12    120     11.5 73   6     19 
51 13    137     10.3 76   6     20 
52 NA    150      6.3 77   6     21 
53 NA     59      1.7 76   6     22 
54 NA     91      4.6 76   6     23 
55 NA    250      6.3 76   6     24 
56 NA    135      8.0 75   6     25 
57 NA    127      8.0 78   6     26 
58 NA     47     10.3 73   6     27 
59 NA     98     11.5 80   6     28 
60 NA     31     14.9 77   6     29 
61 NA    138      8.0 83   6     30

[1] 79.1

In [123]:
x<-subset(x,x["Month"]==5 &x["Ozone"]!="NA")
#x
max(x[["Ozone"]])

[1] 115

In [124]:
ls()

[1] "a"   "bad" "l"   "m"   "n"   "x"   "y"   "z"

In [125]:
 rm(list=ls())

In [126]:
ls()

character(0)

In [2]:
getwd()

[1] "C:/Users/gpalghat006/Documents/GitHub/datasciencecoursera"

In [6]:
x<-4
if (x>3){
    y<-10
} else {
    y<-3
}

y

[1] 10

In [10]:
for(i in 1:10) {
    print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
